### ISSUE TITLE
feat(gallery): A v2 gallery component 

### ISSUE THREAD

**Issue by JayKan** [JayKan/angular2-instagram#5]
@damnko,

**Description**: A version2 gallery component that replaces existing `gallery` component.

**Features**:
- [ ] Swipe left/right touch gestures (Resource: http://hammerjs.github.io/, or some other ones, I'm up to new suggestions)

- [ ] New gallery component should be responsive

**Comment by damnko** [comment]
Hi @JayKan I recently used Swiper.js (http://idangero.us/swiper/demos/#.WNnwUB8tr0o) that's more a slider library than a gesture one but it's the one that Ionic2 uses for it's slide functionality. At the moment we don't need pinch/rotate etc... so maybe this could be a better fit?
There's also an angular2 wrapper (https://github.com/ksachdeva/angular2-swiper), but I don't think I would use it since it has some issues.

Let me know what you think, I have never played with Hammer.js so I won't disdain doing it now ;)

**Comment by JayKan** [comment]
@damnko,

Swiper.js would be also an awesome fit. Why don't you try to implement it in Swiper.js and we can see where we can go from there?
